// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlpnPpRz0Lb-daNvT4nWFAbf1_Gmdm66Q',
    appId: '1:49828557910:web:a74833f3fa49fe0eccb7f7',
    messagingSenderId: '49828557910',
    projectId: 'prest-app',
    authDomain: 'prest-app.firebaseapp.com',
    storageBucket: 'prest-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCM80nizuaUGC4z9bawe-teplSfmtU5w4',
    appId: '1:49828557910:android:fabf1d80e73bd049ccb7f7',
    messagingSenderId: '49828557910',
    projectId: 'prest-app',
    storageBucket: 'prest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWSH6TeGN2DcloBn4UMP3bkcDtGFg-bDY',
    appId: '1:49828557910:ios:325eba4f42cd5155ccb7f7',
    messagingSenderId: '49828557910',
    projectId: 'prest-app',
    storageBucket: 'prest-app.firebasestorage.app',
    iosBundleId: 'com.example.prestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWSH6TeGN2DcloBn4UMP3bkcDtGFg-bDY',
    appId: '1:49828557910:ios:325eba4f42cd5155ccb7f7',
    messagingSenderId: '49828557910',
    projectId: 'prest-app',
    storageBucket: 'prest-app.firebasestorage.app',
    iosBundleId: 'com.example.prestapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlpnPpRz0Lb-daNvT4nWFAbf1_Gmdm66Q',
    appId: '1:49828557910:web:7226cd3c76cec75fccb7f7',
    messagingSenderId: '49828557910',
    projectId: 'prest-app',
    authDomain: 'prest-app.firebaseapp.com',
    storageBucket: 'prest-app.firebasestorage.app',
  );
}
